# Required:
[[plugins]]
repo = 'Shougo/dein.vim'

# neocomplete
[[plugins]]
repo = 'Shougo/neocomplete.vim'
depends = ['Shougo/neoinclude','Shougo/neosnippet','Shougo/neosnippet-snippets']

# neocomplete
[[plugins]]
repo = 'Shougo/neoinclude.vim'

# snippet
[[plugins]]
repo = 'Shougo/neosnippet'
[[plugins]]
repo = 'Shougo/neosnippet-snippets'

# dracula
[[plugins]]
repo = 'dracula/vim'

# resize_window
[[plugins]]
repo = 'simeji/winresizer'

# powerline
[[plugins]]
repo = 'vim-airline/vim-airline'
[[plugins]]
repo = 'vim-airline/vim-airline-themes'
[[plugins]]
repo = 'w0rp/ale'
[[plugins]]
repo = 'ryanoasis/vim-devicons'
