# Required:
[[plugins]]
repo = 'Shougo/dein.vim'

# neocomplete
[[plugins]]
repo = 'Shougo/neocomplete.vim'
depends = ['Shougo/neoinclude','Shougo/neosnippet','Shougo/neosnippet-snippets']

# neocomplete
[[plugins]]
repo = 'Shougo/neoinclude.vim'

# snippet
[[plugins]]
repo = 'Shougo/neosnippet'
[[plugins]]
repo = 'Shougo/neosnippet-snippets'
