[[plugins]]
repo = "zchee/deoplete-clang"
on_ft = "cpp"
depends = "deoplete.nvim"
hook_source = '''
    source ~/.config/nvim/plugins/deoplete-clang.vim
'''

[[plugins]]
repo = "rhysd/vim-clang-format"
on_ft = "cpp"
hook_source= '''
    source ~/.config/nvim/plugins/vim-clang-format.vim
'''

[[plugins]]
repo = 'Shougo/neoinclude.vim'
on_ft = ['c', 'cpp']
depends = "deoplete.nvim"

