[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'simeji/winresizer'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'Shougo/denite.nvim'
hook_add ='''
    source ~/.config/nvim/plugins/denite.vim
'''

[[plugins]]
repo = 'w0rp/ale'
hook_add ='''
    source ~/.config/nvim/plugins/ale.vim
'''

[[plugins]]
repo = 'tpope/vim-fugitive'
hook_add ='''
    source ~/.config/nvim/plugins/fugitive.vim
'''
[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'vim-airline/vim-airline'
hook_add ='''
    source ~/.config/nvim/plugins/airline.vim
'''
[[plugins]]
repo = 'vim-airline/vim-airline-themes'
